---
# tasks file for netapp_confluence_reporter
- name: Gather all volume information
  netapp.ontap.na_ontap_volume_info:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https_validate_certs: "{{ netapp_validate_certs }}"
    vserver: "{{ netapp_vserver }}"
  register: volume_info

- name: Initialize empty list for volume details
  ansible.builtin.set_fact:
    volume_details: []

- name: Gather NFS and CIFS details for each volume
  ansible.builtin.include_tasks: get_share_details.yml
  loop: "{{ volume_info.ontap_info.volume_infos }}"
  loop_control:
    loop_var: volume

- name: Format and update Confluence page
  ansible.builtin.include_tasks: update_confluence.yml
