---
# tasks file for netapp_volume

- name: "Include task to create or modify volume"
  ansible.builtin.include_tasks: _create_volume.yml
  when: netapp_volume_state == 'present'

- name: "Include task to manage volume state (online/offline)"
  ansible.builtin.include_tasks: _manage_state.yml
  when: netapp_volume_state in ['online', 'offline']

- name: "Include task to destroy volume"
  ansible.builtin.include_tasks: _manage_state.yml
  when: netapp_volume_state == 'absent'

- name: "Include task to create a snapshot (custom action)"
  ansible.builtin.include_tasks: _create_snapshot.yml
  when: netapp_volume_state == 'snapshot'
  