---
- name: Extract short names from a list of hostnames
  hosts: localhost
  gather_facts: false

  vars:
    full_hostnames:
      - "web-prod-01"
      - "db-prod-01"
      - "app-dev-01"
      - "bastion-mgmt"

  tasks:
    - name: "Create a new list with the short names"
      ansible.builtin.set_fact:
        short_names: "{{ [ item.split('-')[0] for item in full_hostnames ] }}"

    - name: "Display the new list of short names"
      ansible.builtin.debug:
        var: short_names
